### ISSUE TITLE
Update to PHP7

### ISSUE THREAD

**Issue by oparoz** [turnkeylinux-apps/nextcloud#2]
I've noticed that the plan file still uses php5. It would double the performance if the appliance was to use PHP7.

**Comment by JedMeister** [comment]
Hi @oparoz 

Thanks for posting.

Unfortunately PHP7 is not available in Debian Jessie (what TurnKey v14.x is based on). We could install from 3rd party, but that would mean no auto sec updates for PHP - which we're not very keen on (security and stability are our primary concerns). As PHP7 is the default in Debian Stretch (out now and what v15.x will be based on). So as soon as we've finished the v14.2 release, we'll turn around and start on v15.0. So the next Nextcloud appliance (v15.0) will have it! :smile: 

Also BTW, we use a consolidated [tracker](https://github.com/turnkeylinux/tracker/issues) for all appliances, so in future, please just post there (I'll close this issue and disable issues on this repo in a sec).
